# //=======================================================================
# // Copyright JobPort, IIIT Delhi 2015.
# // Distributed under the MIT License.
# // (See accompanying file LICENSE or copy at
# //  http://opensource.org/licenses/MIT)
# //=======================================================================




# __author__ = 'naman'

sudo: false
language: python
python:
 - "2.7"
env:
  matrix:
   - DJANGO="Django=1.6.10"
install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet
branches:
 only:
  - master
script:
  - cd placement
  - python manage.py test